services:
  fruitaggregator:
    build: ./FruitAggregatorService
    container_name: fruitaggregator
    ports:
      - "5100:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - backend

  fruit:
    build: ./FruitService
    container_name: fruit
    ports:
      - "5200:8080"
    networks:
      - backend

  stock:
    build: ./StockService
    container_name: stock
    ports:
      - "5300:8080"
    networks:
      - backend

networks:
  backend: {}